// Verilator's generated main never calls coveragep()->write(), so `--coverage`
// on its own produces a binary that instruments the design and then throws the
// data away. Measured on Verilator 5.020: coverage.dat is not created at all.
// This replacement main is why the coverage numbers in this repo are real.
//
// cfg.h is generated by the Makefile, so this file does not hard-code the
// design: the same main serves any testbench the flow points it at.
#include "verilated.h"
#include "verilated_cov.h"
#include "cfg.h"
#include VTOP_HEADER

int main(int argc, char** argv) {
    Verilated::debug(0);
    VerilatedContext* contextp = new VerilatedContext;
    contextp->commandArgs(argc, argv);

    VTOP* topp = new VTOP{contextp};

    while (!contextp->gotFinish()) {
        topp->eval();
        if (!topp->eventsPending()) break;
        contextp->time(topp->nextTimeSlot());
    }
    if (!contextp->gotFinish()) {
        VL_PRINTF("+ Exiting without $finish; no events left\n");
    }

    // the whole point: flush the coverage database before the model is gone
    contextp->coveragep()->write(COVERAGE_FILE);

    topp->final();
    delete topp;
    delete contextp;
    return 0;
}
